# Generated by Django 4.2.6 on 2023-10-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="topic",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
